const removeAppTypes = (() => {
  const REMOVE_APPOINTMENT_REQUEST = 'REMOVE_APPOINTMENT_REQUEST';
  const REMOVE_APPOINTMENT_SUCCESS = 'REMOVE_APPOINTMENT_SUCCESS';
  const REMOVE_APPOINTMENT_FAILURE = 'REMOVE_APPOINTMENT_FAILURE';

  return {
    REMOVE_APPOINTMENT_REQUEST,
    REMOVE_APPOINTMENT_SUCCESS,
    REMOVE_APPOINTMENT_FAILURE,
  };
})();

export default removeAppTypes;
