const appointments = (() => {
  const FETCH_APPOINTMENTS_REQUEST = 'FETCH_APPOINTMENTS_REQUEST';
  const FETCH_APPOINTMENTS_SUCCESS = 'FETCH_APPOINTMENTS_SUCCESS';
  const FETCH_APPOINTMENTS_FAILURE = 'FETCH_APPOINTMENTS_FAILURE';

  return { FETCH_APPOINTMENTS_FAILURE, FETCH_APPOINTMENTS_SUCCESS, FETCH_APPOINTMENTS_REQUEST };
})();

export default appointments;
