const suits = (() => {
  const FETCH_SUITS_REQUEST = 'FETCH_SUITS_REQUEST';
  const FETCH_SUITS_FAILURE = 'FETCH_SUITS_FAILURE';
  const FETCH_SUITS_SUCCESS = 'FETCH_SUITS_SUCCESS';

  return { FETCH_SUITS_REQUEST, FETCH_SUITS_FAILURE, FETCH_SUITS_SUCCESS };
})();

export default suits;
