const appointmentTypes = (() => {
  const ADD_APPOINTMENT_REQUEST = 'ADD_APPOINTMENT_REQUEST';
  const ADD_APPOINTMENT_SUCCESS = 'ADD_APPOINTMENT_SUCCESS';
  const ADD_APPOINTMENT_FAILURE = 'ADD_APPOINTMENT_FAILURE';

  return {
    ADD_APPOINTMENT_REQUEST,
    ADD_APPOINTMENT_SUCCESS,
    ADD_APPOINTMENT_FAILURE,
  };
})();

export default appointmentTypes;
